function mainMenu()
    % Create the main menu
    mainFig = figure('Name', 'Planetary Motion Simulator', ...
        'Units', 'normalized', 'Position', [0.1, 0.1, 0.8, 0.8], ...
        'NumberTitle', 'off', 'MenuBar', 'none', 'ToolBar', 'none', ...
        'Color', [0.9, 0.9, 1]);

   

    bgAxes = axes('Parent', mainFig, 'Units', 'normalized', ...
                  'Position', [0, 0, 1, 1]); % Full figure
    backgroundImage = imread('sistem.png');
    image(bgAxes, backgroundImage); % Use `image` for scaling
    set(bgAxes, 'XLim', [1 size(backgroundImage, 2)], ...
                'YLim', [1 size(backgroundImage, 1)], ...
                'XTick', [], 'YTick', []); 
    axis(bgAxes, 'off'); 
    uistack(bgAxes, 'bottom'); % Push to the background



    % Title
    uicontrol('Style', 'text', 'String', 'Planetary Motion Simulator', ...
        'Units', 'normalized', ...
        'Position', [0.2, 0.8, 0.6, 0.1], ...
        'BackgroundColor', [0.9 0.9 1], ...
        'ForegroundColor', '#330066', ...
        'FontName', 'Times New Roman', ...
        'FontWeight', 'Bold', ...
        'FontSize', 24);

    % Documentation Button
    uicontrol('Style', 'pushbutton', 'String', 'Documentation', ...
        'Units', 'normalized', ...
        'Position', [0.3, 0.6, 0.4, 0.1], ...
        'BackgroundColor', '#f3e6ff', ...
        'ForegroundColor', '#330066', ...
        'FontName', 'Times New Roman', ...
        'FontWeight', 'Bold','FontSize',15, ...
        'Callback', @openDocumentation);

    % Graphs & Rotation Button
    uicontrol('Style', 'pushbutton', 'String', 'Graphs & Rotation', ...
        'Units', 'normalized', ...
        'Position', [0.3, 0.4, 0.4, 0.1], ...
        'BackgroundColor', '#f3e6ff', ...
        'ForegroundColor', '#330066', ...
        'FontName', 'Times New Roman', ...
        'FontWeight', 'Bold','FontSize',15, ...
        'Callback', @openGraphsPage);

    % Size Control Button
    uicontrol('Style', 'pushbutton', 'String', 'Planet Size Control', ...
        'Units', 'normalized', ...
        'Position', [0.3, 0.2, 0.4, 0.1], ...
        'BackgroundColor', '#f3e6ff', ...
        'ForegroundColor', '#330066', ...
        'FontName', 'Times New Roman', ...
        'FontWeight', 'Bold','FontSize',15, ...
        'Callback', @openSizeControl);

    % Close Button
    uicontrol('Style', 'pushbutton', 'String', 'Close', ...
        'Units', 'normalized', ...
        'Position', [0.3, 0.05, 0.4, 0.1], ...
        'BackgroundColor', '#f3e6ff', ...
        'ForegroundColor', '#330066', ...
        'FontName', 'Times New Roman', ...
        'FontWeight', 'Bold','FontSize',15, ...
        'Callback', @(~, ~) close(mainFig));


    % Callback Open Documentation
    function openDocumentation(~, ~)
        docPath = 'Documentation.pdf';
        if isfile(docPath)
            open(docPath);
        else
            errordlg('Documentation file not found.', 'File Error');
        end
    end

    % Callback- Open Graphs Page
    function openGraphsPage(~, ~)
        close(mainFig);
        graphsPage();
    end

    % Callback-open Size Control Page
    function openSizeControl(~, ~)
        close(mainFig);
        solarSystemSizeControl(); 
    end
end